default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: shoppinglist.cp5sclqy5fl5.sa-east-1.rds.amazonaws.com
  port: 5432
  database: shoppinglist
  username: shoppinglist
  password: Shoppinglist1q2w!

test:
  <<: *default
  database: shopping-list_test

production:
  <<: *default
  host: <%= ENV['DATABASE_REMOTE'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  database: shoppinglist
  username: shoppinglist
  password: <%= ENV['DATABASE_PASSWORD'] %>
