default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: shopping-list_development

test:
  <<: *default
  database: shopping-list_test

production:
  <<: *default
  host: <%= ENV['DATABASE_URL'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  database: shoppinglist
  username: shoppinglist
  password: <%= ENV['DATABASE_PASSWORD'] %>
